apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: defi-providers
spec:
  rules:
    - host: defi-providers.dappradar.dev
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: defi-providers
              port:
                number: 443

  tls:
    - hosts:
        - defi-providers.dappradar.dev
      secretName: defi-providers-tls