apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: defi-providers
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: dappradar-defi-secret-store
  target:
    name: defi-providers-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: "" # set in overlay
